<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Favourite extends Model
{
    protected $table = 'favourites';
    protected $fillable = ['user_id', 'motelroom_id'];

    public static function validator()
    {
        $validate = [
            'user_id' => 'required|numeric',
            'motelroom_id' => 'required|numeric'
        ];

        return $validate;
    }

    public function store($data)
    {
        return $this->create($data);
    }

    public function addToFavourite($request)
    {
        $data = [
            'user_id' => $request->user_id,
            'motelroom_id' => $request->motelroom_id
        ];

        $favourite = self::store($data);
        return $favourite;

    }

    public function removeFromFavourite($request)
    {
        $data = [
            'user_id' => $request->user_id,
            'motelroom_id' => $request->motelroom_id
        ];

        $favourite = self::remove($data);
        return $favourite;
    }

    public function remove($data)
    {
        return $this->where([['user_id', '=', $data['user_id']], ['motelroom_id', '=', $data['motelroom_id']]])->delete(); // TODO: Change the autogenerated stub
    }
}
